### ISSUE TITLE
Howto cascade converters?

### ISSUE THREAD

**Issue by SchwabenProgger** [thomasgalliker/ValueConverters.NET#12]
Currently I'm using the Tag property, which is kind of a hack :|

```XAML
<vc:IsEmptyConverter x:Key="IsNotEmptyConverter" IsInverted="True" />
<vc:BoolToVisibilityConverter x:Key="BooleanToVisibility" />

<ItemsControl ItemsSource="{Binding Attributes}" 
    Name="AttributesItemsControl"
    Tag="{Binding Attributes, Converter={StaticResource IsNotEmptyConverter}}"
    Visibility="{Binding Tag, ElementName=AttributesItemsControl, Converter={StaticResource BooleanToVisibility}}"/>
```

What do you think about a usage like this? It would require a DependencyProperty 'PreviousConverter' somewhere in a base class and calling it if not null.

```XAML
<vc:BoolToVisibilityConverter IsInverted="True" x:Key="VisibleIfNotEmptyConverter">
    <vc:BoolToVisibilityConverter.PreviousConverter>
        <vc:IsEmptyConverter />
    </vc:BoolToVisibilityConverter.PreviousConverter>
</vc:BoolToVisibilityConverter>

<!-- or -->

<vc:IsEmptyConverter x:Key="BooleanToVisibilityInverted" />
<vc:BoolToVisibilityConverter x:Key="VisibleIfNotEmptyConverter" 
                                IsInverted="True"
                                PreviousConverter="{StaticResource BooleanToVisibilityInverted}"/>

<!-- usage -->
<ItemsControl ItemsSource="{Binding Attributes}" 
    Visibility="{Binding Attributes, Converter={StaticResource VisibleIfNotEmptyConverter}}"/>
```

**Comment by thomasgalliker** [comment]
I would rather create a case-specific value converter in this case: IsNotEmptyToVisibilityConverter which inherits BoolToVisibilityConverter and overrides the protected "Convert" method. Do you see what I mean?
I think the idea with chaining converters introduces unnecessary complexity.

**Comment by SchwabenProgger** [comment]
That is fine for me. I was just thinking that cascading would be more flexible (with the cost of complexity). However I've not checked if there are any other useful cases of combination.

**Comment by thomasgalliker** [comment]
Ok. I rather want to keep this libeary as simple as possible. Hope this still makes it a good value for you.
