### ISSUE TITLE
License in Readme

### ISSUE THREAD

**Issue by lafe** [thomasgalliker/ValueConverters.NET#14]
The license text in the readme states regarding the license

> CrossPlatformLibrary is Copyright © 2016 Thomas Galliker. Free for non-commercial use. For commercial use please contact the author.

This has the wrong project name (copy & paste?) and contradicts the license file that states that the code is licensed under MIT.

**Comment by thomasgalliker** [comment]
True, this is a typo, thanks for reporting. Concerning the contradiction: All of my open source projects come with dual license: As long as you use the project for non-commercial purposes, the MIT license applies. When used commercially, it‘s subject to a small usage fee. Hope that‘s not a no-go for your project. The aim is not to get rich, but to get a fair compensation if it really helps you :-) Always welcome to discuss: linkedin >> thomas galliker
