### ISSUE TITLE
Ideas for new converters

### ISSUE THREAD

**Issue by sa-he** [thomasgalliker/ValueConverters.NET#15]
What do you think of adding the following converters:

- StringIsNullOrEmptyConverter (or adding invertion on StringIsNotNullOrEmptyConverter)
- AddConverter (wich calculates: value 1 parameter)
- SubtractConverter (wich calculates: value - parameter)

Add/Subtract: I am not sure on what datatype it is best to do the calculation. Im my case int is good enough, but what others might need?

```
public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
{
    if (int.TryParse(value?.ToString(), out var basis)
        && int.TryParse(parameter?.ToString(), out var subtract))
        return basis - subtract;

    return value;
}
```

**Comment by thomasgalliker** [comment]
Cool, yes sure. Do you have working code of these (at least the Add/Subtract) converters? You can send them via gist.github.com or as a pull request.
