### ISSUE TITLE
Additional converters?

### ISSUE THREAD

**Issue by sa-he** [thomasgalliker/ValueConverters.NET#17]
StringEqualsMultiValueConverter - verifies if all given values are string.Equal and returns configurable TrueValue or FalseValue.

ReferenceEqualsMultiValueConverter - verifies if all given values are object.ReferenceEqual and returns configurable TrueValue or FalseValue.

StringStartsWith-/EndsWithConverter - verifies if given value.ToString() starts/ends with given parameter and returns configurable TrueValue or FalseValue.

Feel free to let me know if these are converters that you consider helpful for others and want to have included in your lib or not.

**Comment by thomasgalliker** [comment]
Do you have them in a place where I can see them? gist maybe? Just curious what you're going to do with these converters.

**Comment by sa-he** [comment]
I can send you sample code next week. But it does not (yet) use configurable True-/FalseValue, but hard configured e.g. Visibility.

My use cases for the string converters are in ListBoxes or Treeviews. I want to enable / disable / show / hide UIElements according to a bound string which might be e.g. a file name. This way I can e.g. highlight all .txt files in a TreeView.

**Comment by sa-he** [comment]
https://gist.github.com/sa-he/238de39d370b949cfc543635a39e2c36

**Comment by martin-braun** [comment]
@sa-he Your extended converters should always return bool. You surely can also introduce variants for visibility, but at the end only bool is necessary, because you can chain converters using the ValueConverterGroup. 

I.e. you can do this:

```xaml
<vc:ValueConverterGroup x:Key="StringIsNotNullOrEmptyVisibilityConverter">
  <vc:StringIsNotNullOrEmptyConverter />
  <vc:BoolToVisibilityConverter />
</vc:ValueConverterGroup>
```
