### ISSUE TITLE
.Net Core 3 compatibility?

### ISSUE THREAD

**Issue by GF-Huang** [thomasgalliker/ValueConverters.NET#20]
ValueConverters is currently only supported in .Net Framework and Xamarin.Forms projects. .Net Core 3.x also has an IValueConverter interface so we could extend the support for this library too.

**Comment by thomasgalliker** [comment]
True, I was out of time to add netcore3 support. What needs to be done?
- New library for netcoreapps3, link Shared project
- Publish dlls in nuget package
- Anything else?

**Comment by GreatFireWall** [comment]
Just port to `.net standard library`.

**Comment by thomasgalliker** [comment]
Yes, it seems like some manual effort. Thanks for bringing this to the table. I’ll have a look at it as soon as I have some spare time.
