### ISSUE TITLE
Suggestion to rename NullToBoolConverter and IsEmptyConverter

### ISSUE THREAD

**Issue by sa-he** [thomasgalliker/ValueConverters.NET#22]
NullToBoolConverter -> ObjectIsNullConverter
IsEmptyConverter -> EnumerableIsEmptyConverter

**Comment by thomasgalliker** [comment]
I would not rename this converter as I‘ve seen this name in many projects I was consulting for. We could create another class with the name you proposed which inherits from NullToBooleanConverter. (Not really a nice solution, I know).

On the other hand, you have to define x:Keys for each converter anyways. So, what if you just use x:Key=„ObjectIsNullConverter“ in app.xaml?

**Comment by thomasgalliker** [comment]
Or do you want to split the converter into two? Could give a slight improvement in performance. We could sill leave the old converter and mark it as obsolete.

**Comment by sa-he** [comment]
Other projects use these names? To me, this is even more reason to rename. It is only going to be a conflict if other projects use the same namespace (which is unlikely). In my opinion good names tell a consuming developer what the converter is doing. For these two I had to look at the source code in order to understand them.

No, I do not suggest to split a converter.

I just went through the list again and add to the list of rename suggestions these:

```
DateTimeConverter -> DateTimeToStringConverter
VisibilityInverter -> InvertVisibilityConverter  // This one is just to meet the unspoken convention that normally they end with "Converter"
```

**Comment by thomasgalliker** [comment]
True that. Check github for occurances of converter names:
- nulltoboolconverter: 480x
- objecttonullconverter: 17x

I think it is a matter of taste too.

**Comment by sa-he** [comment]
Yes it is. Feel free to decide however you prefere.

**Comment by thomasgalliker** [comment]
I know what you must be thinking now: "Why should I name my stuff as wrong as 480 others did" 😄 But the other 480 will be frustrated if their nulltoboolconverter isn't there anymore. I'll ask some more people of what they think.

**Comment by thomasgalliker** [comment]
True. I will not rename converters as there are many different opinions on names. I prefere the way of inheriting existing converters innorder to create alias class names. Hope that‘s fine.
