### ISSUE TITLE
New version ?

### ISSUE THREAD

**Issue by tranb3r** [thomasgalliker/ValueConverters.NET#26]
Are you going to publish a new version soon ? (last 3 versions were "pre" versions)

**Comment by thomasgalliker** [comment]
Yes, good point. Sorry for the delay. I usually test the pre-releases in unreleased software of my own. But it looks good now for a stable release.

**Comment by thomasgalliker** [comment]
Ok @tranb3r  there was a problem with the build pipeline. Latest version (as by now) is 2.0.20011.1: https://www.nuget.org/packages/ValueConverters/2.0.20011.1
