### ISSUE TITLE
Is there any way to create a composed Converter?

### ISSUE THREAD

**Issue by SuperJMN** [thomasgalliker/ValueConverters.NET#28]
Like a pipeline of Converters?

See: [ValueConverterGroup](https://www.infragistics.com/help/wpf/infragisticswpf~infragistics.controls.primitives.valueconvertergroup)

**Comment by thomasgalliker** [comment]
We were thinking about something some time ago. In the end, converter groups and also multi-binding converters increase complexity to a certain degree. In such cases, would you not better prepare the value in a viewmodel before sending it to the view?

**Comment by SuperJMN** [comment]
That's true for some cases, but, for example, making a Null To Visibility Converter would is quite common and could be composed easily. I think that, at least, it would be nice to let the developer decide where it pays off and where it doesn't. What do you think?

**Comment by thomasgalliker** [comment]
Yes true. Finally, its a case by case decision when you prepare values in the viewmodel and when you use conveters. 
Can you show a use case of such piped/grouped conveters? You want to control the Visibility property of a WPF app, what property in your data context would trigger the visibility change? - I think I would want a bool property in the viewmodel for this purpose. So, a simple BoolToVisibilityConverter would do it. Am I on the wrong path?

**Comment by thomasgalliker** [comment]
@SuperJMN what do you think of this: #31 
I did a small sample too. You'll find it in MainPage.xaml (WPF app).
Let me know if this would be a useful converter.
