### ISSUE TITLE
String reference not set when creating CultureInfo.

### ISSUE THREAD

**Issue by sbeaudoin** [thomasgalliker/ValueConverters.NET#29]
I am using version 2.0.20011.1 of the nuget.

**Symptoms**
I have the following rendering error :

```
System.ArgumentNullException: String reference not set to an instance of a String.
Parameter name: name
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at ValueConverters.ConverterBase.Windows.UI.Xaml.Data.IValueConverter.Convert(Object value, Type targetType, Object parameter, String culture)
   at PlexSync.Dialogs.SelectServerUserDialog.SelectServerUserDialog_obj1_Bindings.Update_ViewModel_IsServerVisible(Boolean obj, Int32 phase)
```

**How I used it**
Here is the resource definition in app.xaml :

```
<Application
   ...
   xmlns:converters="using:ValueConverters" />

   <Application.Resources>
      <ResourceDictionary>
         <converters:BoolToVisibilityConverter x:Key="BoolToVisibility" />
      </ResourceDictionary>
   </Application.Resources>
</Application>
```

Here is where I use it :

```
...
        <Grid Visibility="{x:Bind ViewModel.IsServerVisible, Converter={StaticResource BoolToVisibility}}">
...
```

**Comment by thomasgalliker** [comment]
@sbeaudoin are you sure the ArgumentNullException happens inside of BoolToVisibilityConverter? Are you passing a ConverterParameter somewhere?

What is x:Bind? Shouldn't that be {Binding ...} instead of {x:Bind ...}?

**Comment by sbeaudoin** [comment]
The stack says it happens to boolToVisibilityConverter.  The sample does not show a parameter, so, no.  x:bind is a newer, faster, runtime checked bind.

**Comment by sbeaudoin** [comment]
Anyway, the bind method used is not supposed to influence the value you receive and the call stack.  This is not urgent, in the meantime, I use the one provided with Prism.

**Comment by thomasgalliker** [comment]
Did you have a look at this converter? It's kind of a no-brainer. The CultureInfo mentioned in the stack trace is not used anywhere. Kind of weird. If you find the time to create a small sample which reproduces this problem -> highly welcome.

**Comment by sbeaudoin** [comment]
If you used my code and can't reproduce it, I will not provide more effort and use something else.  Thanks anyway.
