### ISSUE TITLE
Support .NET 5.0

### ISSUE THREAD

**Issue by martin-braun** [thomasgalliker/ValueConverters.NET#34]
> Package 'ValueConverters 2.0.20011.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0-windows7.0'. This package may not be fully compatible with your project.

Would love to see this project updated to support .NET 5.0.

**Comment by thomasgalliker** [comment]
Oh dear, yes sure. Im taking this to my planning.

**Comment by martin-braun** [comment]
Hi @thomasgalliker. I hope I didn't demand something stressful about it. The project compiles and works and I am grateful nonetheless. Thank you for making this public, do not feed stressed about it, it's no blocker whatsoever.

**Comment by thomasgalliker** [comment]
@martin-braun can you please check the latest pre-release nuget and provide some feedback. [https://www.nuget.org/packages/ValueConverters/2.2.7-pre](https://www.nuget.org/packages/ValueConverters/2.2.7-pre)

Thanks a lot.

**Comment by martin-braun** [comment]
@thomasgalliker Thanks for the fix, it works very well. Couldn't spot any issues and the warning is gone. Really appreciate this package, thanks a lot!
