### ISSUE TITLE
Suggestion: support for NoesisGUI

### ISSUE THREAD

**Issue by Aberro** [thomasgalliker/ValueConverters.NET#40]
Maybe add version with NoesisGUI support? It should be easy, just a #if #else in usings section of files. Of course, users could do this themselves, but such support out of the box would be nice.

**Comment by Aberro** [comment]
Uhhuh, not so simple... Your converters use DependencyObject, and it looks like Noesis doesn't support DependencyObjects as converters...

**Comment by thomasgalliker** [comment]
A way to integrate this project into another project would be to create a new integration project. Sonething like Noesis.ValueConverters? But tbh, I have never heard of Noesis :-)

**Comment by Aberro** [comment]
NoesisGUI is WPF based UI for Unity3D (mostly) and native (PC/Mobile/Console) applications. Quite useful for UI-intense games.
In most cases it's fully WPF compatible except in Noesis namespace, but sometimes it requires some fixes to make compatible.

**Comment by thomasgalliker** [comment]
@Aberro while this is a cool idea, I have no capacity to dive into another platform. Ideally, you create your own nuget package and name if ValueConverters.Noesis so that noesis devs will find it.
Have a great day!
