### ISSUE TITLE
[Bug]The Debug.WriteLine in  DebugConverter  was deleted in the Nuget Package

### ISSUE THREAD

**Issue by zmrbak** [thomasgalliker/ValueConverters.NET#44]
Source Code:

namespace ValueConverters
{
    public class DebugConverter : SingletonConverterBase<DebugConverter>
    {
        protected override object Convert(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            Debug.WriteLine("DebugConverter.Convert(value={0}, targetType={1}, parameter={2}, culture={3}",
                value ?? "null",
                (object)targetType ?? "null",
                parameter ?? "null", 
                (object)culture ?? "null");

            return value;
        }

        protected override object ConvertBack(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            Debug.WriteLine("DebugConverter.ConvertBack(value={0}, targetType={1}, parameter={2}, culture={3}",
                 value ?? "null",
                 (object)targetType ?? "null",
                 parameter ?? "null",
                 (object)culture ?? "null");

            return value;
        }
    }
}

The Decompiled code of DebugConverter in  the Nuget Package:

namespace ValueConverters
{
    public class DebugConverter : SingletonConverterBase<DebugConverter>
    {
        protected override object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            return value;
        }

        protected override object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            return value;
        }
    }
}

**Comment by thomasgalliker** [comment]
Ahhh. I see the problem. We compile in RELEASE mode which removes all calls to Debug.*

I will use something similar to what‘s proposee here: https://stackoverflow.com/a/9987984

**Comment by thomasgalliker** [comment]
I created another converter `TraceConverter` which uses Trace.WriteLine instead of Debug.WriteLine. See #55.
