### ISSUE TITLE
[Enhancement] EnumToBoolConverter Support `Enum` ConverterParameter Type

### ISSUE THREAD

**Issue by emako** [thomasgalliker/ValueConverters.NET#46]
## Summary
Please provide a brief summary of your proposal. Two to three sentences is best here.

Support that ConverterParameter is `Enum` and not just `String`.
It can improve the flexibility for `EnumToBoolConverter`.

## API Changes
Include a list of all API changes, additions, subtractions as would be required by your proposal.

EnumToBoolConverter

## Intended Use Case
Provide a detailed example of where your proposal would be used and for what purpose.

```xaml
<RadioButton Content="ON"
             IsChecked="{Binding EditType, Converter={x:Static conv:EnumToBoolConverter.Instance}, ConverterParameter={x:Static local:EditPanelValueType.Switch}, Mode=TwoWay, FallbackValue={markups:False}}" />
```

**Comment by ErickWei** [comment]
cant agree more with your point

**Comment by thomasgalliker** [comment]
Regarding MAUI? Its a shame…
