### ISSUE TITLE
[Enhancement] Could this package support Avalonia?

### ISSUE THREAD

**Issue by emako** [thomasgalliker/ValueConverters.NET#47]
And maybe I can contribute PR for supporting Avalonia.

**Comment by thomasgalliker** [comment]
I have no idea what Avalonia is. So, I guess the answer is rather no. I have no capacity to learn another new UI technology.

**Comment by emako** [comment]
OK, I will try make a ported from this package to [Avalonia](https://github.com/AvaloniaUI/Avalonia) in a new repository.

**Comment by emako** [comment]
https://www.nuget.org/packages/ValueConverters.Avalonia/
