### ISSUE TITLE
[Enhancement] XmlnsPrefix and XmlnsDefinition

### ISSUE THREAD

**Issue by emako** [thomasgalliker/ValueConverters.NET#48]
## Summary
Add XmlnsPrefix to package and then user can simplify the definition of converter.

## API Changes
Example code:
```c#
// AssemblyInfo.cs
[assembly: XmlnsPrefix("https://github.com/thomasgalliker/ValueConverters.NET", "vc")]
[assembly: XmlnsDefinition("https://github.com/thomasgalliker/ValueConverters.NET", "ValueConverters")]
```

After XmlnsPrefix and XmlnsDefinition, user can use following

```xaml
<UserControl xmlns:vc="https://github.com/thomasgalliker/ValueConverters.NET">
</UserControl>
```

instead of 

```xaml
<UserControl xmlns:vc="clr-namespace:ValueConverters;assembly=ValueConverters">
</UserControl>
```

## Intended Use Case
Provide a detailed example of where your proposal would be used and for what purpose.
```xaml
<UserControl xmlns:vc="https://github.com/thomasgalliker/ValueConverters.NET">
</UserControl>
```

**Comment by thomasgalliker** [comment]
@emako can you try the latest nuget pre-release (https://www.nuget.org/packages/ValueConverters/3.1.8-pre and later) if it works as expected?
- The prefix is `c`
- The namespace is `http://schemas.superdev.ch/valueconverters/2016/xaml`

**Comment by emako** [comment]
All right in [3.1.11-pre](https://www.nuget.org/packages/ValueConverters/3.1.11-pre)
