### ISSUE TITLE
[Bug] Shouldn't ValueConverterGroup.ConvertBack() call ConvertBack() instead of Convert()?

### ISSUE THREAD

**Issue by hpablo** [thomasgalliker/ValueConverters.NET#53]
### Description
ValueConverterGroup.ConvertBack() correctly reverses the internal chain of converters, but then calls (via Aggregate()) Convert() on each one. I expected ConvertBack() to call ConvertBack() on the internal converters. 

Is this a bug?

### Steps to Reproduce

1.  Look at the code.

- Version with issue: HEAD

**Comment by thomasgalliker** [comment]
Thanks for reporting this issue. It‘s fixed in #54. An updated nuget will be rolled out soon.
